# Generated by Django 2.0.3 on 2018-03-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='visited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
